const jugadores = [
    {
        player: 'Ospina, David',
        camiseta: 1,
        valuacion: 20,
        posicion: 'Arquero',
        club: 'Napoli',
        partidos: 112,
        goles: 0,
        foto: 'https://www.footyrenders.com/render/david-opsina.png',
    },
    {
        player: 'Cuadrado, Juan',
        camiseta: 11,
        valuacion: 45,
        posicion: 'Centrocampista',
        club: 'Juventus de Turín',
        partidos: 107,
        goles: 9,
        foto: 'https://www.pngkit.com/png/full/126-1265258_feed-rss-juan-cuadrado-colombia-png.pngimgs/cuadrado.png',
    },
    {
        player: 'Mina, Yerry',
        camiseta: 13,
        valuacion: 20,
        posicion: 'Defensor',
        club: 'Everton',
        partidos: 53,
        goles: 8,
        foto: 'https://i.pinimg.com/originals/ad/f6/16/adf616134fffb7894d5fa1302fad18f5.png',
    },
    {
        player: 'Sanchez, Davinson',
        camiseta: 23,
        valuacion: 40,
        posicion: 'Defensor',
        club: 'Tottenham Hotspur',
        partidos: 49,
        goles: 2,
        foto: 'https://www.eje21.com.co/site/wp-content/uploads/2022/01/davinson-sanchez.-imagen-fcf..png',
    },
    {
        player: 'Diaz, Luis',
        camiseta: 14,
        valuacion: 8,
        posicion: 'Delantero',
        club: 'Lverpool',
        partidos: 49,
        goles: 10,
        foto: 'https://cr00.epimg.net/especiales/2022/09/nestorLorenzo/images/luisdiaz.png',
    },
    {
        player: 'Lerma, Jefferson',
        camiseta: 16,
        valuacion: 25,
        posicion: 'Centrocampista',
        club: 'Leeds United',
        partidos: 32,
        goles: 1,
        foto: 'https://cr00.epimg.net/especiales/2022/09/nestorLorenzo/images/jeffersonLerma.png',
    },
    {
        player: 'Barrios, Wilmar',
        camiseta: 5,
        valuacion: 30,
        posicion: 'Centrocampista',
        club: 'Zenit San Petersburgo',
        partidos: 47,
        goles: 2,
        foto: 'https://www.thesportsdb.com/images/media/player/render/j6b81c1638142974.png',
    },
    {
        player: 'Uribe, Mateus',
        camiseta: 7,
        valuacion: 12,
        posicion: 'Centrocampista',
        club: 'Porto',
        partidos: 30,
        goles: 2,
        foto: 'https://www.footyrenders.com/render/Jose-Izquierdo.png',
    },
    {
        player: 'Cardona, Edwin',
        camiseta: 8,
        valuacion: 18,
        posicion: 'Centrocampista',
        club: 'Boca Juniors',
        partidos: 46,
        goles: 6,
        foto: 'https://www.footyrenders.com/render/Edwin-Cardona.png',
    },
    {
        player: 'Moreno, Yayro',
        camiseta: 19,
        valuacion: 35,
        posicion: 'Centrocampista',
        club: 'Medellin',
        partidos: 41,
        goles: 7,
        foto: 'https://img.vavel.com/yairo-moreno-perfil-1591507626300.png',
    },
    {
        player: 'Zapata, Duvan',
        camiseta: 10,
        valuacion: 40,
        posicion: 'Delantero',
        club: 'Atalanta',
        partidos: 32,
        goles: 14,
        foto: 'https://redgol.cl/export/sites/redgol/img/2019/06/27/30gsjr0xlmjulnz227zfxga8l_2.png_355471845.png',
    },
    {
        player: 'Muriel, Luis',
        camiseta: 11,
        valuacion: 30,
        posicion: 'Delantero',
        club: 'Atalanta',
        partidos: 36,
        goles: 8,
        foto: 'https://www.ceroacero.es/img/jogadores/75/752375_med__20210215185548_luis_muriel.png',
    },
    {
        player: 'Borja, Miguel',
        camiseta: 12,
        valuacion: 15,
        posicion: 'Delantero',
        club: 'Gremio',
        partidos: 20,
        goles: 5,
        foto: 'https://uploads-ssl.webflow.com/5fe7644f3e57ba663d4c2656/61379a528213a123fa0d082d_image-removebg-preview%20-%202021-09-07T185854.488.png',
    },
    {
        player: 'Vargas, Camilo',
        camiseta: 13,
        valuacion: 20,
        posicion: 'Arquero',
        club: 'Atlas',
        partidos: 33,
        goles: 1,
        foto: 'https://fcf.com.co//wp-content/uploads/2018/08/VARGAS.png',
    },
    {
        player: 'Bacca, Carlos',
        camiseta: 14,
        valuacion: 10,
        posicion: 'Delantero',
        club: 'Granada',
        partidos: 43,
        goles: 7,
        foto: 'https://s.yimg.com/xe/i/us/sp/v/soccer/wc/players/373235.1.png',
    },
    {
        player: 'Tesillo, William',
        camiseta: 15,
        valuacion: 8,
        posicion: 'Defensor',
        club: 'León',
        partidos: 25,
        goles: 1,
        foto: 'https://i0.wp.com/laesquinarojiblanca.com/wp-content/uploads/2021/11/Tesillo-445x400-2.png?resize=218%2C218&ssl=1',
    },
    {
        player: 'Morelos, Alfredo',
        camiseta: 16,
        valuacion: 20,
        posicion: 'Delantero',
        club: 'Rangers',
        partidos: 15,
        goles: 3,
        foto: 'https://cdn.sofifa.net/players/221/714/20_360.png',
    },
    {
        player: 'Cuesta, Carlos',
        camiseta: 17,
        valuacion: 10,
        posicion: 'Defensor',
        club: 'K. R. C. Genk',
        partidos: 22,
        goles: 1,
        foto: 'https://sortitoutsidospaces.b-cdn.net/megapacks/cutoutfaces/originals/12.00/76047487.png',
    },
    {
        player: 'Radamel, Falcao',
        camiseta: 9,
        valuacion: 12,
        posicion: 'Delantero',
        club: 'Rayo vallecano',
        partidos: 105,
        goles: 304,
        foto: 'https://futbolete.com/apuestas/wp-content/uploads/2022/01/Radamel-Falcao-Free-Picture-PNG.png',
    },
    // Agregar el resto de los jugadores colombianos aquí...
    // ...
];

// Puedes utilizar la matriz 'jugadores' en tu código según tus necesidades
